// Code generated by ./scirpts/enum_alias.go DO NOT EDIT.

package material

import "github.com/Nadim147c/material/dynamic"

const (
	// PlatformPhone is a Platform of type Phone.
	PlatformPhone = dynamic.PlatformPhone
	// PlatformWatch is a Platform of type Watch.
	PlatformWatch = dynamic.PlatformWatch
	// VariantMonochrome is a Variant of type Monochrome.
	VariantMonochrome = dynamic.VariantMonochrome
	// VariantNeutral is a Variant of type Neutral.
	VariantNeutral = dynamic.VariantNeutral
	// VariantTonalSpot is a Variant of type Tonal_spot.
	VariantTonalSpot = dynamic.VariantTonalSpot
	// VariantVibrant is a Variant of type Vibrant.
	VariantVibrant = dynamic.VariantVibrant
	// VariantExpressive is a Variant of type Expressive.
	VariantExpressive = dynamic.VariantExpressive
	// VariantFidelity is a Variant of type Fidelity.
	VariantFidelity = dynamic.VariantFidelity
	// VariantContent is a Variant of type Content.
	VariantContent = dynamic.VariantContent
	// VariantRainbow is a Variant of type Rainbow.
	VariantRainbow = dynamic.VariantRainbow
	// VariantFruitSalad is a Variant of type Fruit_salad.
	VariantFruitSalad = dynamic.VariantFruitSalad
	// Version2021 is a Version of type 2021.
	Version2021 = dynamic.Version2021
	// Version2025 is a Version of type 2025.
	Version2025 = dynamic.Version2025
)
